name: Build Windows Artifact

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ---------- Toolchain setup ----------
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun (if you build with bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.43

      # ---------- Build ----------
      - name: Install JS / Tauri dependencies
        run: bun install   # or `npm ci` / `pnpm install`

      - name: Build application
        run: bun run tauri build --ci   # adjust for npm if needed

      # ---------- Collect & upload artifact ----------
      - name: Upload packaged bundle
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          # Change this if your bundle ends up elsewhere
          path: src-tauri/target/release/bundle/**/*
